// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalShell.Data;

#nullable disable

namespace PortalShell.Migrations
{
    [DbContext(typeof(PortalShellContext))]
    [Migration("20260921174629_AddPortalLinks")]
    partial class AddPortalLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PortalShell.Models.PortalLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PortalLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsEnabled = true,
                            Title = "Service Intake Demo",
                            Url = "#"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsEnabled = true,
                            Title = "Licensing Dashboard",
                            Url = "#"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsEnabled = true,
                            Title = "Application Status",
                            Url = "#"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IsEnabled = false,
                            Title = "Document Requests",
                            Url = "#"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
